const INT_SKILLS = [
  'ATUALIDADES',
  'CIENCIAS',
  'INVESTIGACAO',
  'INTUICAO',
  'MEDICINA',
  'SOBREVIVENCIA',
  'TECNOLOGIA',
  'CRIPTOGRAFIA'
]
const VIG_SKILLS = [
  'FORTITUDE',
  'CONCENTRACAO',
  'VONTADE'
]
const FOR_SKILLS = [
  'ATLETISMO',
  'LUTA'
]
const PRE_SKILLS = [
  'ADESTRAMENTO',
  'DIPLOMACIA',
  'ENGANACAO',
  'INTIMIDACAO',
  'PERCEPCAO'
]
const AGI_SKILLS = [
  'ACROBACIA',
  'CRIME',
  'FURTIVIDADE',
  'INICIATIVA',
  'PILOTAGEM',
  'PONTARIA',
  'REFLEXO'
]
const SKILLS = ['INT', 'VIG', 'FOR', 'PRE', 'AGI']

export { INT_SKILLS, VIG_SKILLS, FOR_SKILLS, PRE_SKILLS, AGI_SKILLS, SKILLS };
